<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <CustomCommands>
      <CustomCommands>
        <Command>
          <type>AfterBuild</type>
          <command></command>
        </Command>
      </CustomCommands>
    </CustomCommands>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4"><IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
<PrivateAssets>all</PrivateAssets>
</PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="Microsoft.Playwright.MSTest" Version="1.56.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.11.0" />
    <PackageReference Include="MSTest.TestFramework" Version="3.11.0" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="References\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="References\" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CAST_Client_Service">
      <HintPath>References\CAST_Client_Service.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Update="cast.properties">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
