# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Define the matrix variable 'dotnet-version' with a list of versions
        dotnet-version: [ '9.0.x' ] 

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies for Scheduler Service
      run: dotnet restore
      working-directory: ./Scheduler_Service
    - name: Build Scheduler Service
      run: dotnet build --no-restore
      working-directory: ./Scheduler_Service
    - name: Test Scheduler Service
      run: dotnet test --verbosity normal --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
      working-directory: ./Scheduler_Service/Tests
    - name: Upload Scheduler Service test results
      uses: actions/upload-artifact@v4
      if: always() 
      with:
        # name: dotnet-results-${{ matrix.dotnet-version }}
        name: scheduler_service-results
        path: ./Scheduler_Service/Tests/TestResults-${{ matrix.dotnet-version }}

    - name: Restore dependencies for File Storage Service
      run: dotnet restore
      working-directory: ./File_Storage_Service
    - name: Build File Storage Service
      run: dotnet build --no-restore
      working-directory: ./File_Storage_Service
    - name: Test File Storage Service
      run: dotnet test --verbosity normal --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
      working-directory: ./File_Storage_Service
    - name: Upload File Storage Service test results
      uses: actions/upload-artifact@v4
      if: always() 
      with:
        # name: dotnet-results-${{ matrix.dotnet-version }}
        name: file_storage_service-results
        path: ./File_Storage_Service/TestResults-${{ matrix.dotnet-version }}

    - name: Restore dependencies for Execution Service
      run: dotnet restore
      working-directory: ./Execution_Service
    - name: Build Execution Service
      run: dotnet build --no-restore
      working-directory: ./Execution_Service
    - name: Test Execution Service
      run: dotnet test --verbosity normal --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
      working-directory: ./Execution_Service/Tests
    - name: Upload Execution Service test results
      uses: actions/upload-artifact@v4
      if: always() 
      with:
        # name: dotnet-results-${{ matrix.dotnet-version }}
        name: execution_service-results
        path: ./Execution_Service/Tests/TestResults-${{ matrix.dotnet-version }}

    - name: Restore dependencies for Logger Service
      run: dotnet restore
      working-directory: ./Logger_Service
    - name: Build Logger Service
      run: dotnet build --no-restore
      working-directory: ./Logger_Service
    - name: Test Logger Service
      run: dotnet test --verbosity normal --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
      working-directory: ./Logger_Service/Logger_Service.Tests
    - name: Upload Logger Service test results
      uses: actions/upload-artifact@v4
      if: always() 
      with:
        # name: dotnet-results-${{ matrix.dotnet-version }}
        name: logger_service-results
        path: ./Logger_Service/Logger_Service.Tests/TestResults-${{ matrix.dotnet-version }}
