name: Execution UI
on:
  push:
    branches: [ "main" ]
    paths: [ "Execution_UI/**" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Define the matrix variable 'dotnet-version' with a list of versions
        dotnet-version: [ '9.0.x' ] 

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies for Execution UI
      run: dotnet restore
      working-directory: ./Execution_UI/Execution_UI
    - name: Build Execution UI
      run: dotnet build --no-restore
      working-directory: ./Execution_UI/Execution_UI
    - name: Test Execution UI
      run: dotnet test --verbosity normal --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
      working-directory: ./Execution_UI/Execution_UI.Tests
    - name: Upload Execution UI test results
      uses: actions/upload-artifact@v4
      if: always() 
      with:
        # name: dotnet-results-${{ matrix.dotnet-version }}
        name: execution_ui-results
        path: ./Execution_UI/Execution_UI.Tests/TestResults-${{ matrix.dotnet-version }}
