name: Java

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v2
        with:
          java-version: '25'
          distribution: 'adopt'

      - name: Build
        run: mvn --batch-mode -DskipTests package
        working-directory: ./CAST_Java_Client_Service

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
        working-directory: ./CAST_Java_Client_Service

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
